const freezeRecords = (records) => Object.freeze(records.map((record) => Object.freeze(record)));

export const LATTICE_EVIDENCE_CLAIM_BOUNDARY =
  "Explanatory source model. This view is not live request telemetry, a deployment observation, or proof of service availability.";

export const textToLatticeEvidenceViews = freezeRecords([
  { id: "end-to-end", label: "End-to-end flow" },
  { id: "adapter", label: "Adapter boundary" },
  { id: "admission", label: "Request admission" },
  { id: "reconciliation", label: "Reconciliation matrix" },
  { id: "blueprint", label: "Service blueprint" },
]);

export const textToLatticeEndToEndFlow = Object.freeze({
  title: "End-to-end state flow",
  label: "Source-model flow",
  tone: "storm-gray",
  condition: "One deliberate submission; no automatic retry",
  diagram: [
    "LOCAL EDIT + PREFLIGHT",
    "├─ reject or cancel → LOCAL ONLY",
    "└─ valid + confirmed deliberate submit",
    "                 ↓",
    "BODYLESS VISITOR-SESSION SETUP",
    "├─ transport or non-204 → STOP",
    "└─ accepted 204",
    "                 ↓",
    "EXACTLY ONE CONTENT POST",
    "├─ held / reject / quota → BOUNDED ERROR",
    "├─ client cancel → END CLIENT WAIT",
    "└─ admitted → FIXED PIPELINE",
    "                 ↓",
    "ANALYZE → DRAFT → DETERMINISTIC CHECK → VERIFY",
    "├─ eligible failure → BOUNDED REANALYZE /",
    "│   REGENERATE OR REPAIR / REVERIFY",
    "└─ otherwise continue",
    "                 ↓",
    "CERTIFY WHEN REQUIRED → HOST RECONCILIATION",
    "├─ releasable closed result → DISPLAY",
    "├─ no releasable output → UNABLE TO ATTEMPT",
    "└─ propagated failure → BOUNDED ERROR",
  ].join("\n"),
  description: "The visitor edits locally. A local preflight rejection or cancellation before submission keeps the text local. A valid, confirmed form submission starts a bodyless visitor-session setup; confirmation alone sends nothing. A setup transport failure or non-204 response stops before content is sent. An accepted 204 permits the still-active canonical client to send its one content request. The Worker may hold, reject, or deny that request before provider work, or admit it to fixed analysis, drafting, deterministic checking, verification, bounded reanalysis or repair when eligible, and certification when required. Host reconciliation displays a valid closed result, withholds unreleasable output as unable-to-attempt, or maps a propagated protocol or pipeline failure to a bounded error. Canceling ends the client wait, but an already admitted claim is not refunded. There is no automatic retry.",
  equivalentSteps: freezeRecords([
    {
      actor: "Visitor and browser",
      action: "Open the modal, read the external-processing boundary, compose text, and run local preflight checks.",
      condition: "Opening, editing, failed preflight, or pre-submit dismissal or cancellation does not call the API. Closing after submission is outside this local-only branch: it only hides the modal and preserves the active request.",
      outcome: "On the local-only branch, the source remains editable in the browser and no submitted prose crosses the network boundary.",
      recovery: "Revise the source locally or close the modal; a later request still requires a deliberate submission.",
    },
    {
      actor: "Visitor",
      action: "Confirm authorization for external processing, then deliberately submit the form.",
      condition: "The source passed local validation and the visitor accepted the disclosed boundary. Confirmation without submission sends nothing.",
      outcome: "The confirmed form submission lets the browser acquire the origin-wide Web Lock and begin this attempt; submission does not promise success.",
      recovery: "Canceling before transmission preserves local work and sends no content.",
    },
    {
      actor: "Browser client and same-origin Worker",
      action: "Send a bodyless visitor-session setup, then, only after an accepted 204, send exactly one content request containing text, requested_mode, and schema_version 1.",
      condition: "A setup transport failure or non-204 response stops the attempt before the content request. Script cannot observe whether the HttpOnly cookie was stored.",
      outcome: "Setup creates or preserves the signed API-scoped cookie without quota or provider work; a missing or invalid cookie on the content request is rejected before both.",
      recovery: "A setup or cookie failure returns a bounded failure. Any later attempt requires a new deliberate submission.",
    },
    {
      actor: "Same-origin Worker and admission authority",
      action: "Validate the exact request and make one atomic daily-quota claim before provider work.",
      condition: "A qualification window closed at receipt, invalid request, unavailable admission authority, or denied quota cannot enter the provider pipeline. Qualification expiry after admission can instead replace the in-progress attempt's output with the held response.",
      outcome: "The Worker returns a finite held, rejection, internal-error, or rate-limited response; an allowed claim becomes an admitted and counted attempt.",
      recovery: "No automatic retry occurs. Retry guidance, when present, still requires another deliberate submission.",
    },
    {
      actor: "Fixed Text to Lattice pipeline",
      action: "Use fixed analysis and candidate generation, deterministic checks, fixed verification, bounded reanalysis or repair and re-verification when eligible, certification when required, and host result reconciliation.",
      condition: "An admitted attempt remains counted after caller disconnect or provider failure and is not refunded.",
      outcome: "The pipeline returns a validated translated, conformant-for-context, review-required, or unable-to-attempt result. A stage failure can close as unable-to-attempt; a propagated failure becomes a bounded machine-readable error.",
      recovery: "Unable-to-attempt contains no transformed text. Provider or stage-decoder failure does not trigger a provider or model fallback.",
    },
    {
      actor: "Browser client",
      action: "Validate the closed response and render the terminal result or error.",
      condition: "Canceling during the request ends the client wait; the browser cannot infer whether the server had already admitted the attempt.",
      outcome: "Cancellation is not shown as success. A valid terminal state remains local while mounted.",
      recovery: "Starting over or retrying is always a new deliberate action; the client never repeats the request automatically.",
    },
  ]),
});

export const textToLatticeAdapterBoundary = Object.freeze({
  title: "Adapter boundary",
  label: "Fixed adapter",
  tone: "storm-gray",
  condition: "The browser payload is exact; this UI uses the fixed auto mode",
  diagram: [
    "BROWSER",
    "text · requested_mode · schema_version",
    "                 ↓ same-origin only",
    "API WORKER",
    "validate · admit · bound",
    "                 ↓ server-only token",
    "FIXED HUGGING FACE ADAPTER + ROUTER",
    "                 ↓ fixed generation calls",
    "QWEN / NSCALE",
    "analysis · candidate generation · repair",
    "                 ↓ bounded stage records",
    "HOST NORMALIZATION + DETERMINISTIC CHECKS",
    "                 ↓ fixed review calls",
    "LLAMA / DEEPINFRA",
    "verification · certification",
    "                 ↓ bounded stage records",
    "EXACT DECODERS + HOST RECONCILIATION",
    "                 ↓",
    "CLOSED RESULT OR BOUNDED ERROR",
    "                 ↓",
    "BROWSER (NO RAW PROVIDER BODY)",
  ].join("\n"),
  description: "The browser submits only text, requested_mode, and schema_version 1 to the same-origin Worker; this UI fixes requested_mode to auto. The browser cannot select a provider, URL, model, prompt, provider header, or credential. After validation and admission, the Worker alone uses a server-only token with the fixed Hugging Face router and adapter. Qwen served by Nscale performs analysis, candidate generation, and repair; host normalization and deterministic checks constrain its stage records. Llama served by DeepInfra performs verification and certification. Exact wire decoders admit bounded stage records, then host validation and reconciliation classify the public result. Malformed, oversized, unavailable, or invalid upstream output fails closed: bounded stage policy may yield unable-to-attempt, while propagated failure is mapped to a sanitized error. Raw provider bodies and credentials never return to the browser, and there is no automatic retry or alternate provider or model fallback.",
  equivalentSteps: freezeRecords([
    {
      actor: "Browser client",
      action: "Send the exact same-origin request fields: text, requested_mode fixed to auto by this UI, and schema_version 1.",
      condition: "The client cannot supply a provider URL, provider or model name, prompt, provider header, account credential, or server token.",
      outcome: "The request reaches only /api/lattice under the named same-origin capability.",
      recovery: "A request outside the closed envelope is rejected; the browser does not redirect it to another target.",
    },
    {
      actor: "API Worker",
      action: "Validate the route, origin, media envelope, request shape, input bounds, session cookie, rate shape, server configuration, and atomic admission claim.",
      condition: "Provider work begins only after those boundaries accept the content request.",
      outcome: "Rejected or unavailable requests terminate with bounded errors before provider work; allowed requests enter the fixed adapter.",
      recovery: "The Worker fails closed when configuration, admission, or request evidence is invalid.",
    },
    {
      actor: "Fixed server adapter",
      action: "Call only the Hugging Face chat-completions router using the server-held provider credential and fixed model destinations.",
      condition: "Qwen/Qwen3-4B-Instruct-2507 served by Nscale performs analysis, candidate generation, and repair; meta-llama/Llama-3.1-8B-Instruct served by DeepInfra performs verification and certification.",
      outcome: "Submitted text and the stage-specific server prompts cross to Hugging Face and the corresponding fixed provider destination under their policies; credentials remain server-only.",
      recovery: "A target cannot be replaced by a browser choice, provider fallback, model fallback, or transport retry.",
    },
    {
      actor: "Host pipeline and exact decoders",
      action: "Use exact wire decoders to admit only bounded stage records, then combine normalized records with deterministic host evidence.",
      condition: "Malformed, oversized, hostile, unavailable, or invalid provider output does not become semantic authority.",
      outcome: "Host reconciliation produces a closed public result, withholds unreleasable output as unable-to-attempt, or propagates a failure as a sanitized bounded error.",
      recovery: "Only bounded same-model correction or repair allowed by stage policy may occur; failure does not switch targets.",
    },
    {
      actor: "Browser client",
      action: "Receive only the validated API result or bounded public error.",
      condition: "Raw provider bodies, prompts, provider credentials, and diagnostic internals are not part of the browser response.",
      outcome: "The UI can render a finite terminal state without exposing the provider transport.",
      recovery: "Invalid, oversized, HTML, or non-JSON responses are rejected locally and are never presented as success.",
    },
  ]),
});

export const textToLatticeAdmissionStateMachine = Object.freeze({
  title: "Request-admission subsystem state machine",
  label: "Admission states",
  tone: "storm-gray",
  condition: "Setup never claims quota; provider work follows one allowed atomic claim",
  diagram: [
    "REQUEST RECEIVED",
    "        ↓",
    "QUALIFICATION OPEN? ── no → HELD 503",
    "        │ yes",
    "        ↓",
    "EXACT SETUP OR CONTENT ENVELOPE?",
    "├─ setup → 204 SIGNED COOKIE",
    "│          no admission · no provider",
    "└─ content",
    "        ↓",
    "VALID COOKIE + INPUT + RATE + CONFIG?",
    "├─ no → BOUNDED PRE-ADMISSION REJECTION",
    "└─ yes",
    "        ↓",
    "ONE ATOMIC DAILY-QUOTA CLAIM",
    "├─ denied → 429 · no provider",
    "├─ unavailable / invalid → 500 · fail closed",
    "└─ allowed → ADMITTED + COUNTED",
    "              ├─ window expires → HELD 503",
    "              └─ window open → FIXED PIPELINE",
  ].join("\n"),
  description: "On receipt, the Worker first requires an open qualification window; otherwise it returns held 503. An exact bodyless setup establishes or preserves the signed cookie and returns 204 without admission or provider work. A content request must have a valid signed cookie, exact envelope and bounded input, pass the rate shaper, and find valid server configuration. Failure is rejected before admission. The Worker then makes exactly one atomic claim against 30 accepted transformations globally per UTC day and 3 per cooperating canonical client cookie jar per UTC day. A denied claim returns 429 without provider work; unavailable or invalid admission evidence fails closed. An allowed claim is admitted and counted before the fixed pipeline. It is not refunded after disconnect or provider failure, and the pipeline makes no second shared quota claim. Qualification expiry during processing returns the held response rather than success.",
  equivalentSteps: freezeRecords([
    {
      actor: "API Worker qualification gate",
      action: "Capture and enforce the qualification window when the request arrives and throughout the bounded request.",
      condition: "When the window is closed at receipt, no claim or provider work occurs. If it expires during an admitted pipeline, an accepted counting claim and provider work may already exist.",
      outcome: "Return HTTP 503 with upstream_unavailable as the held response; do not represent the request as successful.",
      recovery: "A later attempt requires a fresh deliberate submission after the service is available; no automatic retry occurs.",
    },
    {
      actor: "API Worker session branch",
      action: "Accept only the exact bodyless visitor-session setup and establish or preserve the signed, HttpOnly, API-scoped cookie.",
      condition: "The setup uses the required Accept value, has no Content-Type, and has no body bytes.",
      outcome: "Return 204. The setup makes no quota claim and no provider call.",
      recovery: "Invalid setup is rejected. A transport or non-204 setup failure prevents the browser from sending content.",
    },
    {
      actor: "API Worker content branch",
      action: "Resolve the signed visitor cookie and validate exact path, method, origin, headers, JSON envelope, requested mode, schema version, and input bounds.",
      condition: "A missing cookie returns 428; an invalid or undeclared cookie returns 403; other closed-boundary violations return their finite 4xx response.",
      outcome: "Invalid content requests stop before atomic admission and before provider work.",
      recovery: "The browser keeps its local source; another attempt requires another deliberate action.",
    },
    {
      actor: "Rate, configuration, and admission boundaries",
      action: "Apply the edge rate shaper, require the server-only token, then make exactly one atomic quota claim.",
      condition: "The quota is 30 accepted transformations globally per UTC day and 3 per cooperating canonical client with an ordinary persistent cookie jar per UTC day.",
      outcome: "A denied claim returns 429 without provider work. Unavailable or invalid admission evidence returns a bounded internal error and fails closed.",
      recovery: "Retry timing may be shown when valid, but a retry is never initiated automatically. Intentional cookie clearing is outside the scoped per-cookie-jar claim; the global bound remains authoritative.",
    },
    {
      actor: "Admitted request",
      action: "Enter the fixed Text to Lattice pipeline after the allowed atomic claim.",
      condition: "The accepted claim occurs before provider work and there is no second shared quota check within the pipeline.",
      outcome: "The attempt remains counted after caller disconnect or provider failure and is not refunded.",
      recovery: "The pipeline returns a valid closed result including unable-to-attempt, a held response on qualification expiry, or a propagated bounded error; no provider or model fallback occurs.",
    },
  ]),
});

export const textToLatticeReconciliation = Object.freeze({
  label: "Closed outcomes",
  tone: "storm-gray",
  condition: "Host evidence determines the public result; transport failures remain errors",
  diagram: [
    "CLOSED HOST + VERIFIER EVIDENCE",
    "├─ material candidate + all required gates",
    "│                              → TRANSLATED",
    "├─ unchanged source + positive conformance",
    "│                 → CONFORMANT FOR CONTEXT",
    "├─ material + bounded review-only issue",
    "│                         → REVIEW REQUIRED",
    "└─ no releasable source or candidate",
    "                         → UNABLE TO ATTEMPT",
    "",
    "REQUEST / PROVIDER / RESPONSE CONTRACT FAILURE",
    "                              → FINITE ERROR",
  ].join("\n"),
  description: "Closed host and verifier evidence reconciles into one of four result statuses. A materially changed candidate that clears the required gates is translated. An unchanged source with positive selected-context conformance is conformant-for-context. A material, semantically releasable candidate with only a bounded lower-priority review issue is review-required. If neither a conformant source nor an eligible candidate can be exposed, the host withholds transformed text and returns unable-to-attempt. A transport, provider, Worker, or client-response contract failure that propagates beyond bounded stage handling remains a finite error and is never relabeled as a result.",
});

export const textToLatticeReconciliationRows = freezeRecords([
  {
    label: "translated",
    tone: "blue-green",
    value: "Condition and evidence: the assembled candidate is materially different from the source, its analysis, candidate, and verification records share a coherent revision, deterministic document checks pass, and semantic verification plus any required bounded-window or whole-document certification gate accepts it. Host reconciliation: expose the checked assembled candidate with its validated layer and count metadata. Public outcome: Latticed text. Recovery: read and review the result, close it, or deliberately start over.",
  },
  {
    label: "conformant-for-context",
    tone: "blue-green",
    value: "Condition and evidence: the assembled text is unchanged, every relevant passage was marked retain-if-conformant, positive conformance was confirmed, revision records are coherent, deterministic checks pass, and any required bounded-window or whole-document certification gate accepts it. Host reconciliation: return the unchanged source only under the explicit selected-context classification. Public outcome: Source fits this context. Recovery: read and review the unchanged source, close it, or deliberately start over.",
  },
  {
    label: "review-required",
    tone: "storm-gray",
    value: "Condition and evidence: a materially different candidate is revision-coherent, deterministically safe, semantically releasable, and passes any required bounded-window or whole-document certification, but retains an explicit bounded lower-priority review-only issue. Host reconciliation: expose the eligible material draft without upgrading it to translated. Public outcome: Review needed, with the instruction to review before relying on it. Recovery: review the draft and findings, close it, or deliberately start over.",
  },
  {
    label: "unable-to-attempt",
    tone: "red-orange",
    value: "Condition and evidence: the pipeline cannot expose either a positively conformant source or a candidate that clears the required release and revision-coherence gates. Host reconciliation: suppress any candidate, return null text and null primary layer identifiers with no used layers, and never relabel withheld material as success. Public outcome: No Latticed result; nothing was changed. Recovery: review the bounded finding, revise the local source if useful, close it, or deliberately start over.",
  },
  {
    label: "Bounded request or provider error",
    tone: "red-orange",
    value: "Condition and evidence: request validation, admission, deadline, provider transport, provider output, exact decoding, or Worker execution propagates a declared machine-readable failure instead of being absorbed by bounded stage policy into a valid result. Host reconciliation: map only the bounded public error code and valid retry metadata; do not expose raw provider bodies or relabel the failure as a result. Public outcome: the existing classified error message and recovery action, never success. Recovery: correct an actionable local problem or make a later deliberate submission; operator-side failure requires service recovery, and there is no automatic retry or provider fallback.",
  },
  {
    label: "Client invalid-response error",
    tone: "red-orange",
    value: "Condition and evidence: the response shape, status-to-error pairing, content type, byte bound, JSON, exact schema version, or closed result decoder fails, including an invalid HTTP 200 envelope. Host reconciliation: reject the response as invalid_response and expose no transformed text. Public outcome: a finite client error, never a partial or successful result. Recovery: keep the local source and deliberately try later; the client does not retry or route content elsewhere.",
  },
]);

export const textToLatticeServiceBlueprintLanes = freezeRecords([
  {
    lane: "Visitor action",
    value: "Read boundary → Compose and preflight → Confirm and submit → Wait or cancel → Read, review, close, or start over",
    emphasis: "action",
  },
  {
    lane: "Frontstage",
    value: "Disclose purpose and external processing → Show actionable validation → Announce finite working state → Label the closed result or error",
  },
  {
    lane: "Browser backstage",
    value: "Stay local before confirmation → Acquire the origin-wide Web Lock → Send bodyless setup → Send exactly one content request → Validate the closed response",
  },
  {
    lane: "API backstage",
    value: "Validate session and request → Apply rate and configuration gates → Make one atomic quota claim → Run bounded analysis, drafting, checks, verification, repair, and certification → Reconcile the public result → Return no-store response",
  },
  {
    lane: "Provider support",
    value: "Hugging Face router → Qwen served by Nscale for analysis, candidate generation, and repair → Llama served by DeepInfra for verification and certification",
  },
  {
    lane: "Evidence and recovery",
    value: "Local correction before transmission → Bounded rejection or held response → No automatic retry or fallback → New deliberate action for any later attempt",
  },
  {
    lane: "Data boundary",
    value: "Local source before confirmation → Content in bounded API and provider request memory → Validated result or bounded error to browser → No application content sink",
  },
]);

export const textToLatticeServiceBlueprintStages = freezeRecords([
  {
    stage: "BP-01",
    title: "Read the boundary",
    actor: "Visitor and frontstage",
    action: "Open the modal and read the purpose, limits, external-processing warning, restricted-information warning, fixed model roles, and provider-policy limitation.",
    condition: "Opening the interface does not submit text.",
    outcome: "The visitor can make an informed choice before any transformation request.",
    recovery: "If the capability is unavailable, the explanatory material remains readable and no text is transmitted.",
    boundary: "No submitted prose crosses a network boundary.",
  },
  {
    stage: "BP-02",
    title: "Compose and preflight",
    actor: "Visitor and browser",
    action: "Enter one to 700 Unicode-aware words while the client uses its fixed auto requested mode, and run the published local structural and size checks.",
    condition: "Failed preflight remains local and cannot enable submission.",
    outcome: "Valid source is ready for deliberate authorization; invalid source stays editable without truncation or relabeling.",
    recovery: "Revise locally; the API and providers remain untouched.",
    boundary: "Source and local findings remain in the browser document.",
  },
  {
    stage: "BP-03",
    title: "Authorize external processing",
    actor: "Visitor",
    action: "Choose Process with external service after reviewing the warning, or cancel.",
    condition: "Only a confirmed explicit form submission can start the request sequence; checking confirmation alone sends nothing, and there is no implicit submission, prefetch, background send, or automatic retry.",
    outcome: "Authorization precedes the bodyless setup and the one content request for this attempt.",
    recovery: "Canceling or dismissing before submission preserves local work without transmission.",
    boundary: "No setup or content request exists without confirmation.",
  },
  {
    stage: "BP-04",
    title: "Establish session, submit, and admit",
    actor: "Browser, API Worker, and admission authority",
    action: "Under one Web Lock, send exact bodyless setup, then one exact content request; validate it and make one atomic quota claim before provider work.",
    condition: "Setup failure prevents content; missing or invalid cookie and other invalid requests stop before admission; a denied claim stops before provider work; client cancellation may occur at any wait point.",
    outcome: "The request is held, rejected, denied, the browser wait is canceled, or the request is admitted and counted. An admitted claim is not refunded.",
    recovery: "A bounded failure is shown; cancellation ends the browser wait. Every later attempt requires a new deliberate submission.",
    boundary: "Setup contains no source. Content enters bounded API request memory only in the content request; secrets remain server-only and quota state contains no content.",
  },
  {
    stage: "BP-05",
    title: "Analyze with fixed generator",
    actor: "Worker, fixed adapter, Hugging Face, Nscale, and Qwen",
    action: "Create bounded prompts, protect source spans, and use the fixed Qwen generator for atomization, classification, and planning.",
    condition: "The visitor cannot select the provider, URL, model, prompt, header, or credential; remote clarification stays disabled.",
    outcome: "A bounded analysis record proceeds, or invalid or unavailable upstream behavior fails closed.",
    recovery: "Only bounded same-model schema correction may occur within the pipeline; there is no provider or model fallback.",
    boundary: "Qwen analysis prompts containing submitted text cross through Hugging Face to Nscale. Llama and DeepInfra receive later verification and certification prompts. Raw provider bodies do not reach the browser.",
  },
  {
    stage: "BP-06",
    title: "Draft and deterministically check",
    actor: "Fixed Qwen generator and host validators",
    action: "Draft a material candidate and check source coverage, protected spans, polarity, quantities, modality, uncertainty, and bounded work limits.",
    condition: "Rejected candidates and provider-authored issue prose cannot become new semantic authority.",
    outcome: "A candidate advances within the finite repair budget, or the pipeline closes without a usable transformation.",
    recovery: "Return unable-to-attempt with no transformed text or a bounded error when no candidate clears the gates.",
    boundary: "Only bounded prompts and candidate records exist in request memory and provider processing; the application defines no persistent content sink.",
  },
  {
    stage: "BP-07",
    title: "Verify and classify",
    actor: "Fixed Llama verifier and certifier, DeepInfra, exact decoders, and host validators",
    action: "Return forced-name lattice_verification_wire_v1 verification and lattice_certification_wire_v1 certification records; exact decoders and host validators combine them with deterministic evidence, then the host classifies the public outcome.",
    condition: "A canonical forced tool call may finish with tool_calls. Compatibility content requires stop. Invalid tool or compatibility envelopes, other invalid finish reasons, and invalid decoded records fail closed and cannot be relabeled as success.",
    outcome: "Return translated, conformant-for-context, review-required, unable-to-attempt, or a finite request error.",
    recovery: "Bounded policy repair may occur; otherwise close without fallback. Unable-to-attempt carries no transformed text.",
    boundary: "Verification and certification prompts and candidate text cross the external-provider boundary in bounded request memory.",
  },
  {
    stage: "BP-08",
    title: "Return, retain locally, or start over",
    actor: "API Worker, browser, and visitor",
    action: "Return a no-store response, validate it in the browser, then read, review, close, or deliberately start another attempt.",
    condition: "Invalid, oversized, HTML, non-JSON, or interrupted responses are not rendered as success. Closing only hides the modal and preserves active work; component unmount tears down the active client wait.",
    outcome: "A valid result or bounded error is visible locally while mounted.",
    recovery: "A new attempt requires a new explicit action and never routes content elsewhere automatically.",
    boundary: "Application request memory is released; external-provider handling remains governed by provider policies and is not proven by repository source.",
  },
]);
