export const LATTICE_USAGE_POLICY = Object.freeze({
  version: "text-to-lattice-demo.v8",
  purpose: "Portfolio demonstration only; not a copywriting, fiction-writing, or nonfiction-writing service.",
  endpoint: "/api/text-to-lattice/lease",
  requestBody: "none",
  sourceTransmission: "the official hah.dev client sends no source or output",
  visitor: Object.freeze({
    limit: 3,
    windowSeconds: 24 * 60 * 60,
    identity: "opaque HMAC-signed, host-only HttpOnly browser cookie scoped to the Text to Lattice API path",
    applicationRetentionTargetSeconds: 24 * 60 * 60 + 60,
  }),
  globalRequests: Object.freeze({
    limit: 40,
    windowSeconds: 60,
    applicationRetentionTargetSeconds: 2 * 60,
    scope: "actionable lease requests admitted service-wide before Siteverify or lease actions",
  }),
  globalDailyRequests: Object.freeze({
    limit: 3_000,
    windowSeconds: 24 * 60 * 60,
    window: "UTC calendar day",
    applicationRetentionTargetSeconds: 24 * 60 * 60 + 60,
    scope: "actionable lease requests admitted service-wide as an exact free-tier budget guard",
  }),
  globalAttempts: Object.freeze({
    limit: 8,
    windowSeconds: 60,
    applicationRetentionTargetSeconds: 2 * 60,
  }),
  globalGrants: Object.freeze({
    limit: 100,
    windowSeconds: 24 * 60 * 60,
    applicationRetentionTargetSeconds: 24 * 60 * 60 + 60,
  }),
  activeLeases: Object.freeze({
    limit: 8,
    perVisitorLimit: 1,
    ttlSeconds: 45 * 60,
    renewalIntervalSeconds: 10 * 60,
    minimumRenewalIntervalSeconds: 5 * 60,
    maximumLifetimeSeconds: 4 * 60 * 60,
    applicationRetentionTargetSeconds: 46 * 60,
    maximumApplicationRetentionTargetSeconds: 4 * 60 * 60 + 60,
  }),
  providerRecoveryHistoryDays: 30,
  enforcement: Object.freeze({
    authority: "one globally named SQLite-backed Cloudflare Durable Object",
    exactRequestAdmission: Object.freeze({
      limit: 40,
      windowSeconds: 60,
      scope: "service-wide",
      evaluatedAfter: "request safety, control-credential validation, cheap acquisition challenge establishment, and location shaping",
      evaluatedBefore: "Turnstile Siteverify or lease acquisition, renewal, and release actions",
      role: "exact downstream-work admission boundary; hostile requests still consume the public Worker and one admission call",
    }),
    exactDailyRequestAdmission: Object.freeze({
      limit: 3_000,
      windowSeconds: 24 * 60 * 60,
      window: "UTC calendar day aligned with the provider's Free-plan reset",
      scope: "service-wide",
      evaluatedBefore: "Turnstile Siteverify or lease acquisition, renewal, and release actions",
      role: "exact daily downstream-work and state-write budget boundary; requests denied by it still consume one admission call",
    }),
    leaseCredential: Object.freeze({
      format: "HMAC-authenticated bearer containing a 192-bit opaque lease identifier and signed absolute expiry",
      validation: "signature, canonical encoding, and expiry are checked before control shaping or Durable Object access",
      storage: "only the opaque lease identifier is stored by the Durable Object",
      keyManagement: "lease credentials and visitor cookies use distinct Cloudflare encrypted Worker secrets",
      replayBoundary: "per-lease and shared location shapers; exact lifecycle checks at the global authority",
    }),
    humanAttestation: Object.freeze({
      provider: "Cloudflare Turnstile",
      action: "text_to_lattice",
      hostname: "verify.hah.dev",
      frameOrigin: "https://verify.hah.dev",
      framePath: "/turnstile/",
      browserIsolation: "Turnstile runs only in a dedicated cross-origin frame and cannot read the hah.dev document under the browser same-origin policy",
      messageBoundary: "exact parent and frame origins, exact Window source, closed versioned schemas, and a 144-bit single-request correlation identifier",
      tokenMaximumCharacters: 2_048,
      validitySeconds: 300,
      singleUse: true,
      sourceTransmission: "the official verification frame sends no source or output",
      secretBinding: "TURNSTILE_SECRET_KEY",
      siteKeyBinding: "TURNSTILE_SITE_KEY",
      role: "server-validated, single-use acquisition attestation before grant accounting",
    }),
    ingressLocationShaper: Object.freeze({
      methods: "all methods reaching the exact Worker route",
      binding: "LATTICE_INGRESS_SHAPER",
      limit: 40,
      windowSeconds: 60,
      scope: "each Cloudflare location",
      evaluatedAfter: "exact origin and pathname routing",
      evaluatedBefore: "query, method, request-safety, secret, credential, challenge, or singleton work",
      role: "earliest method-agnostic permissive load shedder; it does not erase or exactly bound billed Worker invocations",
    }),
    pathLocationShaper: Object.freeze({
      methods: "POST, PATCH, and DELETE",
      binding: "LATTICE_PATH_SHAPER",
      limit: 40,
      windowSeconds: 60,
      scope: "each Cloudflare location",
      role: "combined permissive load shedder after actor and method shaping; not an accounting authority",
    }),
    locationShaper: Object.freeze({
      method: "POST",
      binding: "LATTICE_ACQUIRE_SHAPER",
      limit: 24,
      windowSeconds: 60,
      scope: "each Cloudflare location",
      role: "permissive load shedder; not an accounting authority",
    }),
    releaseLocationShaper: Object.freeze({
      method: "DELETE",
      binding: "LATTICE_RELEASE_SHAPER",
      limit: 20,
      windowSeconds: 60,
      scope: "each Cloudflare location",
      role: "independent permissive load shedder; not an accounting authority",
    }),
    renewalLocationShaper: Object.freeze({
      method: "PATCH",
      binding: "LATTICE_RENEWAL_SHAPER",
      limit: 12,
      windowSeconds: 60,
      scope: "each Cloudflare location",
      role: "independent permissive load shedder; not an accounting authority",
    }),
    releaseLeaseLocationShaper: Object.freeze({
      method: "DELETE",
      binding: "LATTICE_RELEASE_LEASE_SHAPER",
      limit: 4,
      windowSeconds: 60,
      scope: "each authenticated lease credential in each Cloudflare location",
      actorKeyRequired: true,
      evaluatedBefore: "releaseLocationShaper",
      role: "per-lease control-abuse load shedder; not an accounting authority",
    }),
    renewalLeaseLocationShaper: Object.freeze({
      method: "PATCH",
      binding: "LATTICE_RENEWAL_LEASE_SHAPER",
      limit: 4,
      windowSeconds: 60,
      scope: "each authenticated lease credential in each Cloudflare location",
      actorKeyRequired: true,
      evaluatedBefore: "renewalLocationShaper",
      role: "per-lease control-abuse load shedder; not an accounting authority",
    }),
    legitimateBurstBasis: Object.freeze({
      validatedAcquisitions: 8,
      coldStartPostsPerAcquisition: 2,
      maximumColdStartPosts: 16,
      maximumNewLeaseReleases: 8,
      maximumCarriedLeaseReleases: 8,
      maximumReleaseCalls: 16,
      maximumConcurrentRenewalCalls: 8,
      maximumPathCalls: 40,
      maximumExactAdmissionCalls: 32,
    }),
    edgeFloodProtection: Object.freeze({
      plan: "Cloudflare Free",
      path: "/api/text-to-lattice/lease",
      characteristic: "IP",
      limit: 48,
      windowSeconds: 10,
      mitigationSeconds: 10,
      requiredBeforeDeployment: true,
      availabilityUrl: "https://developers.cloudflare.com/waf/rate-limiting-rules/#availability",
      role: "best-effort flood protection; not exact global accounting",
    }),
    publicGetPaths: "unrestricted",
  }),
  freeTierBasis: Object.freeze({
    asOf: "2026-09-08",
    workerRequestsPerDay: 100_000,
    durableObjectRequestsPerDay: 100_000,
    durableObjectRowsReadPerDay: 5_000_000,
    durableObjectRowsWrittenPerDay: 100_000,
    durableObjectGigabyteSecondsPerDay: 13_000,
    durableObjectMemoryMegabytes: 128,
    durableObjectMemoryGigabytes: 0.128,
    secondsPerUtcDay: 86_400,
    maximumSingletonDurationGigabyteSecondsPerDay: 11_059.2,
    durableObjectDurationHeadroomGigabyteSecondsPerDay: 1_940.8,
    maximumRenewalsPerLease: 47,
    maximumRenewalIntervalsPerActiveSlotPerUtcDay: 288,
    maximumAcceptedRenewalsPerUtcDayAtActiveCap: 2_304,
    maximumNewGrantsPerRollingDay: 100,
    maximumCarriedLeaseReleasesPerUtcDay: 8,
    maximumReleaseTransitionsPerUtcDay: 108,
    maximumProtocolLifecycleActionsPerUtcDay: 2_512,
    maximumProtocolChallengeCallsPerUtcDay: 100,
    maximumProtocolPublicWorkerCallsPerUtcDay: 2_612,
    maximumProtocolAdmissionCallsPerUtcDay: 2_512,
    maximumProtocolDirectDurableObjectRequestsPerUtcDay: 5_024,
    protocolActionHeadroomUnderDailyAdmissionCap: 488,
    maximumNominalSuccessfulIngressCallsPerLocationPerUtcDay: 57_600,
    maximumNominalAdmissionCallsPerLocationPerUtcDay: 57_600,
    maximumAdmissionMutationsPerUtcDay: 3_000,
    downstreamLifecycleLatencyBudgetingAssumptionSeconds: 60,
    downstreamLifecycleLatencyAssumptionIsHardCeiling: false,
    downstreamLifecycleLatencyDeploymentRequirement:
      "measure admission-to-action latency and recalculate carryover if it can exceed the assumption",
    budgetedPriorDayActionCarryoverCallsPerUtcDay: 40,
    maximumBudgetedPrimaryActionCallsPerUtcDay: 3_040,
    maximumCompensatingReleaseCallsPerUtcDay: 3_040,
    maximumBudgetedLifecycleCallsPerUtcDay: 6_080,
    maximumCurrentDayAdmissionExpiryEvents: 3_000,
    budgetedPriorDayAdmissionExpiryCarryoverEvents: 40,
    maximumAttemptExpiryEventsPerUtcDay: 100,
    maximumPriorDayGrantAndVisitorExpiryEvents: 100,
    maximumLeaseExpiryEventsPerUtcDay: 108,
    maximumUtcRolloverEventsPerUtcDay: 1,
    maximumUnderlyingExpiryMomentsPerUtcDay: 3_349,
    alarmCoalescingWindowSeconds: 60,
    maximumAlarmBucketsPerUtcDay: 1_440,
    alarmMaximumRetriesPerEvent: 6,
    alarmMaximumAttemptsPerEvent: 7,
    alarmRetrySpillWindowSeconds: 126,
    alarmSchedulingModel: "one UTC-minute-coalesced alarm per singleton at a time",
    maximumCarriedAlarmSequencesPerUtcDay: 1,
    maximumPriorDayAlarmRetrySpillInvocations: 7,
    maximumBudgetedAlarmInvocationsPerUtcDay: 10_087,
    maximumBudgetedDurableObjectRequestsPerDay: 73_767,
    maximumRowsWrittenPerStateChangingTransaction: 2,
    stateRowOperationPerMutation: "one state put or delete",
    alarmRowOperationPerMutation: "one setAlarm or deleteAlarm, including alarm cleanup",
    maximumRequestTriggeredPruneMutationsPerUtcDay: 3_349,
    maximumBudgetedStateChangingTransactionsPerDay: 22_516,
    maximumBudgetedDurableObjectRowsReadPerDay: 73_767,
    maximumBudgetedDurableObjectRowsWrittenPerDay: 45_032,
    durableObjectRequestHeadroomPerDay: 26_233,
    durableObjectRowsReadHeadroomPerDay: 4_926_233,
    durableObjectRowsWrittenHeadroomPerDay: 54_968,
    verificationFrameWorkerCallsForDailyGrants: 0,
    verificationFrameHosting: "Cloudflare Workers Static Assets with no Worker script invocation; static asset requests are documented free and unlimited",
    scopedSingleLocationNominalIngressBasis: true,
    workerRequestBudgetGuarantee: false,
    workerRequestBudgetLimitation: "every request invokes the Worker before an in-Worker shaper can reject it; IP-local WAF and location-local permissive counters cannot guarantee aggregate daily traffic",
    adversarialTrafficIncluded: "up to the combined local shaper at one location; distributed traffic and permissive overshoot are excluded",
    scope: "Durable Object requests, SQLite row reads and writes, alarm invocations, and the static full-day duration bound for one 128 MB singleton; Worker billing, CPU, real runtime, permissive-counter overshoot, other account workloads, and distributed hostile traffic require provider-side measurement",
    exhaustionMode: "Free-plan quota exhaustion fails closed; it does not incur usage overage",
    workerLimitsUrl: "https://developers.cloudflare.com/workers/platform/limits/",
    staticAssetsBillingUrl: "https://developers.cloudflare.com/workers/static-assets/billing-and-limitations/",
    durableObjectPricingUrl: "https://developers.cloudflare.com/durable-objects/platform/pricing/",
    durableObjectAlarmsUrl: "https://developers.cloudflare.com/durable-objects/api/alarms/",
  }),
  failureMode: "fail-closed; canonical HTML, Markdown, JSON, JSON-LD, sitemap, and llms files remain unrestricted",
});
