import { sharedRequirements } from "../content/siteContent.js";
import { documentsForProject } from "../content/projectDocuments.js";

export const PROJECT_CONTENT_VERSION = "hah-portfolio-projects.v1";
export const PROJECT_CONTENT_UPDATED = "2026-09-08";

export const sharedAssuranceStandards = Object.freeze(sharedRequirements.map(({ id }) => id));

export const LATTICE_DOCUMENTATION_RESOURCES = Object.freeze(
  documentsForProject("lattice").map((document) => Object.freeze({
    id: document.id,
    artifactId: document.artifactId,
    label: document.label,
    title: document.title,
    url: document.htmlUrl,
    markdownUrl: document.markdownUrl,
    htmlMediaType: document.htmlMediaType,
    markdownMediaType: document.markdownMediaType,
    scope: document.scope,
    icon: "backpack4",
    opensInNewTab: false,
  })),
);

export const projects = Object.freeze([
  Object.freeze({
    id: "lattice",
    slug: "lattice",
    name: "Lattice",
    type: "SoftwareSourceCode",
    canonicalPath: "/projects/lattice/",
    url: "https://github.com/howardhayden/lattice",
    icon: "pen-fill",
    thesis: "Lattice turns linguistic register into an explicit, testable system.",
    summary: Object.freeze([
      "Lattice turns linguistic register into an explicit, testable system.",
      "It separates meaning from expression by decomposing content into semantic atoms that candidate prose must preserve. Outputs are evaluated in order of safety, semantic fidelity, accessibility, clarity, domain correctness, register fit, and ornament, preventing style from obscuring instructions, altering causality, or assuming relative education, while welcoming inference.",
      "Its Relational Systems Register connects embodied experience, relationships, institutions, causality, and ethical stakes through consequential detail, subtext, and systems-conscious realism.",
      "Lattice demonstrates that expressive language can be distinctive without becoming semantically unaccountable.",
    ]),
    capabilities: Object.freeze([
      "Semantic atomization",
      "Ordered candidate evaluation",
      "Passage-level register selection",
      "Relational Systems Register",
    ]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://github.com/howardhayden/lattice"]),
    limitations: Object.freeze([
      "The hah.dev Text to Lattice demonstrator is browser-local, requires WebGPU, and accepts at most 700 words.",
      "A review-required draft is not certified as semantically equivalent.",
    ]),
    emphasis: Object.freeze(["linguistic register", "semantic fidelity", "relational systems"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "governs-linguistic-register-for", target: "fog-of-sea", scope: "naval learning and operational uncertainty" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "chorus", scope: "social and epistemic systems" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "evenward", scope: "selected embodied guidance and care" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "Documentation", url: "https://github.com/howardhayden/lattice", icon: "backpack4", opensInNewTab: true }),
      ...LATTICE_DOCUMENTATION_RESOURCES,
    ]),
    publication: Object.freeze({ label: "September 2026", value: "2026-09", precision: "month" }),
    status: "public",
    interaction: "lattice-demo",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "in-keeping",
    slug: "in-keeping",
    name: "IN KEEPING",
    type: "SoftwareApplication",
    canonicalPath: "/projects/in-keeping/",
    url: "https://inkeep.ing/",
    icon: "bricks",
    thesis: "Local-first library continuity lab with user-created workspaces, explicit persistence, integrity-linked revisions, structured safeguards, and notebooks.",
    summary: Object.freeze([
      "Local-first library continuity lab with user-created workspaces, explicit persistence, integrity-linked revisions, structured safeguards, and notebooks. Models dependencies and access paths; records custody, fixity, rights, metadata, conditions, decisions, and recovery actions; preserves provenance and continuity through disruption and handoff.",
    ]),
    capabilities: Object.freeze(["User-created workspaces", "Integrity-linked revisions", "Custody and fixity records", "Continuity and recovery planning"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://inkeep.ing/?view=reports"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["provenance", "continuity", "access paths"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "operationalizes", target: "provenance-continuity", scope: "custody, fixity, recovery, and handoff" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "Technical report", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "Public notice", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
  }),
  Object.freeze({
    id: "fog-of-sea",
    slug: "fog-of-sea",
    name: "FOG OF SEA",
    type: "VideoGame",
    canonicalPath: "/projects/fog-of-sea/",
    url: "https://fogofsea.app/",
    icon: "airplane-engines",
    thesis: "Naval strategy game with cozy vibes.",
    summary: Object.freeze([
      "Naval strategy game with cozy vibes.",
      "Single-player naval strategy learning game implementing nested stochastic matrices within deterministic systems, local-first privacy with resilient data handling, and accessibility, through a cozy-sublime, tactical and diegetic interface.",
    ]),
    capabilities: Object.freeze(["Naval strategy learning", "Deterministic systems", "Local-first data handling", "Accessible tactical interaction"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["operational uncertainty", "naval learning"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "naval learning and operational uncertainty" })]),
    resources: Object.freeze([
      Object.freeze({ label: "Systems Atlas", url: "https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
  }),
  Object.freeze({
    id: "chorus",
    slug: "chorus",
    name: "CHORUS",
    type: "VideoGame",
    canonicalPath: "/projects/chorus/",
    url: "https://chorus.observer/",
    icon: "diagram-3",
    thesis: "Social simulation of influence, uncertainty, and collective belief.",
    summary: Object.freeze([
      "Social simulation of influence, uncertainty, and collective belief.",
      "Multi-agent social simulation game modeling disinformation propagation, algorithmic amplification, social capital, and cross-scenario effects through interconnected social actors, procedural scenario generation, cross-system state effects, and coherency validation at network scale.",
    ]),
    capabilities: Object.freeze(["Multi-agent social systems", "Disinformation propagation", "Procedural scenarios", "Cross-system coherence validation"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://chorus.observer/notebooks/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["social systems", "epistemic systems", "collective belief"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "social and epistemic systems" })]),
    resources: Object.freeze([
      Object.freeze({ label: "Documentation", url: "https://chorus.observer/notebooks/", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "Concept Map", url: "https://chorus.observer/documentation/chorus-concept-map.html", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "CSD Matrix", url: "https://chorus.observer/documentation/chorus-csd-matrix.html", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
  }),
  Object.freeze({
    id: "evenward",
    slug: "evenward",
    name: "Evenward.rest",
    type: "SoftwareApplication",
    canonicalPath: "/projects/evenward/",
    url: "https://evenward.rest/",
    icon: "tree",
    thesis: "A privacy-conscious, self-regulation studio prototype designed around movement, attention, pattern, knowledge, and play.",
    summary: Object.freeze(["A privacy-conscious, self-regulation studio prototype designed around movement, attention, pattern, knowledge, and play."]),
    capabilities: Object.freeze(["Movement guidance", "Attention and pattern practice", "Privacy-conscious local interaction"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://evenward.rest/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["embodied interaction", "care", "self-regulation"]),
    relationships: Object.freeze([Object.freeze({ relation: "selectively-applies-lattice-to", target: "lattice", scope: "embodied guidance and care" })]),
    resources: Object.freeze([]),
    publication: Object.freeze({ label: "July 2026", value: "2026-07", precision: "month" }),
    status: "public",
  }),
  Object.freeze({
    id: "medium",
    slug: "medium",
    name: "Medium",
    type: "CollectionPage",
    canonicalPath: "/projects/medium/",
    url: "https://medium.com/@howardhayden",
    icon: "archive",
    thesis: "The quiet infrastructure that shapes how we live, work, and act under and in preparation for pressure.",
    summary: Object.freeze(["The quiet infrastructure that shapes how we live, work, and act under and in preparation for pressure."]),
    capabilities: Object.freeze([]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://medium.com/@howardhayden"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["infrastructure", "work under pressure"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([]),
    publication: Object.freeze({ label: "June 2026–present", value: "2026-06", precision: "open-range" }),
    status: "ongoing",
  }),
]);

export function projectBySlug(slug) {
  return projects.find((project) => project.slug === slug) ?? null;
}
