import { documentsForProject } from "../content/projectDocuments.js";

export const PROJECT_CONTENT_VERSION = "hah-portfolio-projects.v7";
export const PROJECT_CONTENT_UPDATED = "2026-09-12";

export const LATTICE_DOCUMENTATION_RESOURCES = Object.freeze(
  documentsForProject("lattice").map((document) => Object.freeze({
    id: document.id,
    artifactId: document.artifactId,
    label: document.label,
    title: document.title,
    url: document.htmlUrl,
    markdownUrl: document.markdownUrl,
    htmlMediaType: document.htmlMediaType,
    markdownMediaType: document.markdownMediaType,
    scope: document.scope,
    icon: "backpack4",
    opensInNewTab: false,
  })),
);

export const LATTICE_RELEASE_QUALIFICATION_RESOURCE = Object.freeze({
  label: "Text to Lattice Release Qualification",
  url: "https://hah.dev/documentation/text-to-lattice/TEXT-TO-LATTICE-RELEASE-QUALIFICATION.md",
  icon: "backpack4",
  opensInNewTab: false,
});

export const projects = Object.freeze([
  Object.freeze({
    id: "lattice",
    slug: "lattice",
    name: "Lattice",
    type: "SoftwareSourceCode",
    canonicalPath: "/projects/lattice/",
    url: "https://github.com/howardhayden/lattice",
    icon: "pen-fill",
    thesis: "Lattice makes linguistic register explicit, testable, and accountable to meaning.",
    summary: Object.freeze([
      "Lattice makes linguistic register explicit, testable, and accountable to meaning.",
      "It separates meaning from expression by decomposing content into semantic atoms that candidate prose must preserve, then evaluates outputs in order of safety, semantic fidelity, accessibility, clarity, domain correctness, register fit, and ornament. Its Relational Systems Register connects embodied experience, relationships, institutions, causality, and ethical stakes through consequential detail, subtext, and systems-conscious realism, demonstrating that expressive language can remain distinctive without becoming semantically unaccountable.",
    ]),
    capabilities: Object.freeze([
      "Semantic atomization",
      "Ordered candidate evaluation",
      "Passage-level register selection",
      "Relational Systems Register",
    ]),
    technologies: Object.freeze(["JavaScript", "Node.js", "npm", "WebGPU", "Cloudflare Workers", "Wrangler"]),
    evidence: Object.freeze(["https://github.com/howardhayden/lattice"]),
    limitations: Object.freeze([
      "The hah.dev Text to Lattice demonstrator is browser-local, requires WebGPU, and accepts at most 700 words.",
      "A review-required draft is not certified as semantically equivalent.",
      "The demonstrable release uses Cloudflare’s official testing profile; it provides no production anti-bot assurance, and its public reusable token can occupy all eight shared slots, so availability is not assured.",
    ]),
    emphasis: Object.freeze(["linguistic register", "semantic fidelity", "relational systems"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "governs-linguistic-register-for", target: "fog-of-sea", scope: "naval learning and operational uncertainty" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "chorus", scope: "social and epistemic systems" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "evenward", scope: "selected embodied guidance and care" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "Lattice Source Repository", url: "https://github.com/howardhayden/lattice", icon: "backpack4", opensInNewTab: true }),
      ...LATTICE_DOCUMENTATION_RESOURCES,
      LATTICE_RELEASE_QUALIFICATION_RESOURCE,
    ]),
    publication: Object.freeze({ label: "September 2026", value: "2026-09", precision: "month" }),
    status: "public",
    interaction: "lattice-demo",
    interactiveRelease: "enabled",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "in-keeping",
    slug: "in-keeping",
    name: "IN KEEPING",
    type: "SoftwareApplication",
    canonicalPath: "/projects/in-keeping/",
    url: "https://inkeep.ing/",
    icon: "bricks",
    thesis: "IN KEEPING keeps a library’s evidence, obligations, and recovery paths legible through change.",
    summary: Object.freeze([
      "IN KEEPING keeps a library’s evidence, obligations, and recovery paths legible through change.",
      "This local-first continuity lab gives people explicit workspaces, persistence, integrity-linked revisions, structured safeguards, and notebooks. It models dependencies and access paths; records custody, fixity, rights, metadata, conditions, decisions, and recovery actions; and preserves provenance through disruption and handoff.",
    ]),
    capabilities: Object.freeze(["User-created workspaces", "Integrity-linked revisions", "Custody and fixity records", "Continuity and recovery planning"]),
    technologies: Object.freeze(["TypeScript", "JavaScript", "React", "Node.js", "Vite", "npm", "Cloudflare Workers", "Wrangler"]),
    evidence: Object.freeze(["https://inkeep.ing/?view=reports"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["provenance", "continuity", "access paths"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "operationalizes", target: "provenance-continuity", scope: "custody, fixity, recovery, and handoff" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "IN KEEPING Technical Report", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "IN KEEPING Public Notice", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "fog-of-sea",
    slug: "fog-of-sea",
    name: "FOG OF SEA",
    type: "VideoGame",
    canonicalPath: "/projects/fog-of-sea/",
    url: "https://fogofsea.app/",
    icon: "airplane-engines",
    thesis: "FOG OF SEA turns naval uncertainty into a quiet, learnable field of consequence.",
    summary: Object.freeze([
      "FOG OF SEA turns naval uncertainty into a quiet, learnable field of consequence.",
      "This single-player strategy game nests stochastic matrices within deterministic systems so that uncertainty remains observable without becoming arbitrary. Local-first privacy, resilient data handling, and accessibility support a cozy-sublime interface in which tactical information remains diegetic and decisions carry legible consequences.",
    ]),
    capabilities: Object.freeze(["Naval strategy learning", "Deterministic systems", "Local-first data handling", "Accessible tactical interaction"]),
    technologies: Object.freeze(["TypeScript", "JavaScript", "GLSL", "React", "Node.js", "Three.js", "Vite", "npm", "WebGL", "Cloudflare Workers", "Wrangler"]),
    evidence: Object.freeze(["https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["operational uncertainty", "naval learning"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "naval learning and operational uncertainty" })]),
    resources: Object.freeze([
      Object.freeze({ label: "FOG OF SEA Systems Atlas", url: "https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "chorus",
    slug: "chorus",
    name: "CHORUS",
    type: "VideoGame",
    canonicalPath: "/projects/chorus/",
    url: "https://chorus.observer/",
    icon: "diagram-3",
    thesis: "CHORUS makes collective belief visible as a system of influence, uncertainty, and consequence.",
    summary: Object.freeze([
      "CHORUS makes collective belief visible as a system of influence, uncertainty, and consequence.",
      "This multi-agent social simulation models disinformation propagation, algorithmic amplification, social capital, and cross-scenario effects through interconnected actors. Procedural scenarios and network-scale coherence checks keep state changes traceable as one system’s pressures become another system’s conditions.",
    ]),
    capabilities: Object.freeze(["Multi-agent social systems", "Disinformation propagation", "Procedural scenarios", "Cross-system coherence validation"]),
    technologies: Object.freeze(["TypeScript", "JavaScript", "React", "Next.js", "Node.js", "Vite", "npm", "Cloudflare Workers", "Wrangler"]),
    evidence: Object.freeze(["https://chorus.observer/notebooks/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["social systems", "epistemic systems", "collective belief"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "social and epistemic systems" })]),
    resources: Object.freeze([
      Object.freeze({ label: "CHORUS Notebooks", url: "https://chorus.observer/notebooks/", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "CHORUS Concept Map", url: "https://chorus.observer/documentation/chorus-concept-map.html", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "CHORUS CSD Matrix", url: "https://chorus.observer/documentation/chorus-csd-matrix.html", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "evenward",
    slug: "evenward",
    name: "Evenward.rest",
    type: "SoftwareApplication",
    canonicalPath: "/projects/evenward/",
    url: "https://evenward.rest/",
    icon: "tree",
    thesis: "Evenward.rest treats self-regulation as an ecology of movement, attention, knowledge, and play.",
    summary: Object.freeze([
      "Evenward.rest treats self-regulation as an ecology of movement, attention, knowledge, and play.",
      "This privacy-conscious studio prototype brings embodied guidance, pattern practice, and local interaction into one quiet environment. Its parts are designed to reinforce one another, allowing care to emerge through relationships among movement, attention, knowledge, and play rather than through a single prescribed routine.",
    ]),
    capabilities: Object.freeze(["Movement guidance", "Attention and pattern practice", "Privacy-conscious local interaction"]),
    technologies: Object.freeze(["TypeScript", "JavaScript", "React", "Next.js", "Node.js", "Three.js", "npm", "WebGL"]),
    evidence: Object.freeze(["https://evenward.rest/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["embodied interaction", "care", "self-regulation"]),
    relationships: Object.freeze([Object.freeze({ relation: "selectively-applies-lattice-to", target: "lattice", scope: "embodied guidance and care" })]),
    resources: Object.freeze([
      Object.freeze({ label: "Evenward.rest Studio", url: "https://evenward.rest/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "July 2026", value: "2026-07", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "medium",
    slug: "medium",
    name: "Medium",
    type: "CollectionPage",
    canonicalPath: "/projects/medium/",
    url: "https://medium.com/@howardhayden",
    icon: "archive",
    thesis: "These essays trace the quiet infrastructure that shapes how people act under pressure.",
    summary: Object.freeze([
      "These essays trace the quiet infrastructure that shapes how people act under pressure.",
      "They examine the routines, institutions, tools, and maintenance work that make action possible before a crisis becomes visible. Each essay follows relationships among preparation, constraint, and consequence so that ordinary systems can be understood as conditions of collective life rather than as background.",
    ]),
    capabilities: Object.freeze([]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://medium.com/@howardhayden"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["infrastructure", "work under pressure"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Howie’s Medium Articles", url: "https://medium.com/@howardhayden", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "June 2026–present", value: "2026-06", precision: "open-range" }),
    status: "ongoing",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "lms-reimplementation-proposal",
    slug: "lms-reimplementation-proposal",
    name: "LMS Reimplementation Proposal",
    type: "DigitalDocument",
    canonicalPath: "/projects/lms-reimplementation-proposal/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "diagram-3",
    thesis: "The LMS Reimplementation Proposal reframed MUDEC’s LMS decision around institutional feasibility and long-term consequences.",
    summary: Object.freeze([
      "The LMS Reimplementation Proposal reframed MUDEC’s LMS decision around institutional feasibility and long-term consequences.",
      "I rewrote an unsolicited internal proposal to implement MUDEC LMS, gaining approval after a prior proposer’s denial by accounting for resource allocation, costs and benefits, stakeholders, the market, legal concerns, and long-term impacts.",
    ]),
    capabilities: Object.freeze(["Proposal redevelopment", "Resource allocation", "Cost-benefit analysis", "Stakeholder analysis", "Market analysis", "Legal analysis", "Long-term impact forecasting"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["This portfolio record describes an internal proposal and does not publish the proposal itself."]),
    emphasis: Object.freeze(["business analysis", "institutional decision-making", "long-term planning"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "LMS Reimplementation Proposal record", url: "https://www.linkedin.com/in/howardhayden/details/projects/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "February 2023", value: "2023-02", precision: "month" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "chromebook-management",
    slug: "chromebook-management",
    name: "Chromebook Management",
    type: "SoftwareApplication",
    canonicalPath: "/projects/chromebook-management/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "bricks",
    thesis: "Chromebook Management translated Sierra ILS device states into an internal workflow people could interpret and act on.",
    summary: Object.freeze([
      "Chromebook Management translated Sierra ILS device states into an internal workflow people could interpret and act on.",
      "I developed an internal web application that contextualized, activated, and deactivated Chromebooks while presenting differing Sierra ILS statuses in user-interpretable terms.",
    ]),
    capabilities: Object.freeze(["Device-status contextualization", "Chromebook activation", "Chromebook deactivation", "User-interpretable status presentation"]),
    technologies: Object.freeze(["Jekyll", "Ruby on Rails", "Google Cloud Platform", "Node.js", "Sierra ILS"]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["This portfolio record describes an internal application and does not expose the application or institutional data."]),
    emphasis: Object.freeze(["library systems", "device management", "status interpretation"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Chromebook Management record", url: "https://www.linkedin.com/in/howardhayden/details/projects/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2022 – November 2022", value: "2022-08", start: "2022-08", end: "2022-11", precision: "month-range" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "finding-freedom-summer-traveling-exhibit",
    slug: "finding-freedom-summer-traveling-exhibit",
    name: "Finding Freedom Summer Traveling Exhibit",
    type: "CreativeWork",
    canonicalPath: "/projects/finding-freedom-summer-traveling-exhibit/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "archive",
    thesis: "The Finding Freedom Summer Traveling Exhibit was an OhioLINK-associated collaborative project supported through Miami University Libraries.",
    summary: Object.freeze([
      "The Finding Freedom Summer Traveling Exhibit was an OhioLINK-associated collaborative project supported through Miami University Libraries.",
      "The project involved Sierra ILS and Ruby on Rails and was completed with Miami University Libraries web-services contributors Ken Irwin, Meng Qu, and Jerry Yarnetsky.",
    ]),
    capabilities: Object.freeze(["Collaborative exhibit support", "Library web-services collaboration"]),
    technologies: Object.freeze(["Sierra ILS", "Ruby on Rails"]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["The supplied record identifies collaborators, association, and technologies but does not assign individual implementation responsibilities."]),
    emphasis: Object.freeze(["traveling exhibits", "OhioLINK", "library web services"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Finding Freedom Summer Traveling Exhibit contributor: Ken Irwin", url: "https://www.linkedin.com/in/ken-irwin-08a87ab5/", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "Finding Freedom Summer Traveling Exhibit contributor: Meng Qu", url: "https://www.linkedin.com/in/mengqu/", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "Finding Freedom Summer Traveling Exhibit contributor: Jerry Yarnetsky", url: "https://www.linkedin.com/in/jerry-yarnetsky/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "October 2021 – December 2021", value: "2021-10", start: "2021-10", end: "2021-12", precision: "month-range" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "information-studies-and-digital-citizenship",
    slug: "information-studies-and-digital-citizenship",
    name: "Information Studies and Digital Citizenship",
    type: "Course",
    canonicalPath: "/projects/information-studies-and-digital-citizenship/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "backpack4",
    thesis: "Information Studies and Digital Citizenship framed emerging technology as a subject of business, design, and responsible participation.",
    summary: Object.freeze([
      "Information Studies and Digital Citizenship framed emerging technology as a subject of business, design, and responsible participation.",
      "I designed an Emerging Technology in Business and Design course at Miami University with instructional librarians, including contributor Jaclynn Spraetz of Miami University Libraries.",
    ]),
    capabilities: Object.freeze(["Course design", "Emerging-technology instruction design", "Instructional-librarian collaboration"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["This record documents course design; it does not claim that the course was delivered or independently taught by the author."]),
    emphasis: Object.freeze(["digital citizenship", "emerging technology", "business and design"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Information Studies and Digital Citizenship record", url: "https://www.linkedin.com/in/howardhayden/details/projects/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "May 2021", value: "2021-05", precision: "month" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "comparative-database-design-and-data-analytics",
    slug: "comparative-database-design-and-data-analytics",
    name: "Comparative Database Design and Data Analytics with Various DBMS",
    type: "SoftwareSourceCode",
    canonicalPath: "/projects/comparative-database-design-and-data-analytics/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "diagram-3",
    thesis: "This comparative database study tested how different database models shape design, performance, warehousing, and real-time analysis.",
    summary: Object.freeze([
      "This comparative database study tested how different database models shape design, performance, warehousing, and real-time analysis.",
      "Across non-concurrent, non-sequential, interdepartmental undergraduate courses, I designed, performance-tuned, and scripted SQL, MongoDB, ArangoDB, and Neo4j databases; engineered, documented, and tested a scalable MySQL data warehouse with Git-logged changes; and separately used database virtualization and Google BigQuery for optimized real-time analytics queries.",
    ]),
    capabilities: Object.freeze(["Comparative database design", "Database performance tuning", "Data-warehouse engineering", "Database virtualization", "Real-time analytics querying", "Change logging and versioning"]),
    technologies: Object.freeze(["SQL", "MongoDB", "ArangoDB", "Neo4j", "MySQL", "Git", "Google BigQuery"]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["The work occurred across non-concurrent, non-sequential, interdepartmental undergraduate courses and is presented as one comparative line of study rather than one continuous implementation."]),
    emphasis: Object.freeze(["database systems", "data warehousing", "performance analysis"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Comparative Database Design and Data Analytics with Various DBMS record", url: "https://www.linkedin.com/in/howardhayden/details/projects/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2021 – May 2022", value: "2021-08", start: "2021-08", end: "2022-05", precision: "month-range" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "ux-optimization-case-study",
    slug: "ux-optimization-case-study",
    name: "UX Optimization Case Study",
    type: "Report",
    canonicalPath: "/projects/ux-optimization-case-study/",
    url: "https://www.linkedin.com/in/howardhayden/details/projects/",
    icon: "tree",
    thesis: "The UX Optimization Case Study connected observed library-site behavior to iterative design and statistical evaluation.",
    summary: Object.freeze([
      "The UX Optimization Case Study connected observed library-site behavior to iterative design and statistical evaluation.",
      "Across non-concurrent, non-sequential, interdepartmental undergraduate courses concerning the Miami University Libraries index page, I combined field observation, interviews, contextual inquiry, heuristic evaluation, card sorting, usability testing, design artifacts, Bayesian forecasting, A/B experiments, and multivariate statistical analysis in R and Python.",
    ]),
    capabilities: Object.freeze(["User interviews", "Contextual inquiry", "Heuristic evaluation", "Card sorting", "Usability testing", "Cognitive walkthroughs", "Task and journey analysis", "A/B testing", "Bayesian inference", "Multivariate regression", "Analysis of variance"]),
    technologies: Object.freeze(["Wireshark", "R", "Python"]),
    evidence: Object.freeze(["https://www.linkedin.com/in/howardhayden/details/projects/"]),
    limitations: Object.freeze(["The research occurred across non-concurrent, non-sequential, interdepartmental undergraduate courses and is presented as one case-study line rather than one continuous study."]),
    emphasis: Object.freeze(["user experience research", "library web design", "experimental analysis"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "UX Optimization Case Study record", url: "https://www.linkedin.com/in/howardhayden/details/projects/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2021 – December 2022", value: "2021-08", start: "2021-08", end: "2022-12", precision: "month-range" }),
    status: "completed",
    readmeAfterFirstParagraph: true,
  }),
]);

export function projectBySlug(slug) {
  return projects.find((project) => project.slug === slug) ?? null;
}
