import { documentsForProject } from "../content/projectDocuments.js";

export const PROJECT_CONTENT_VERSION = "hah-portfolio-projects.v6";
export const PROJECT_CONTENT_UPDATED = "2026-09-09";

export const LATTICE_DOCUMENTATION_RESOURCES = Object.freeze(
  documentsForProject("lattice").map((document) => Object.freeze({
    id: document.id,
    artifactId: document.artifactId,
    label: document.label,
    title: document.title,
    url: document.htmlUrl,
    markdownUrl: document.markdownUrl,
    htmlMediaType: document.htmlMediaType,
    markdownMediaType: document.markdownMediaType,
    scope: document.scope,
    icon: "backpack4",
    opensInNewTab: false,
  })),
);

export const LATTICE_RELEASE_QUALIFICATION_RESOURCE = Object.freeze({
  label: "Text to Lattice Release Qualification",
  url: "https://hah.dev/documentation/text-to-lattice/TEXT-TO-LATTICE-RELEASE-QUALIFICATION.md",
  icon: "backpack4",
  opensInNewTab: false,
});

export const projects = Object.freeze([
  Object.freeze({
    id: "lattice",
    slug: "lattice",
    name: "Lattice",
    type: "SoftwareSourceCode",
    canonicalPath: "/projects/lattice/",
    url: "https://github.com/howardhayden/lattice",
    icon: "pen-fill",
    thesis: "Lattice makes linguistic register explicit, testable, and accountable to meaning.",
    summary: Object.freeze([
      "Lattice makes linguistic register explicit, testable, and accountable to meaning.",
      "It separates meaning from expression by decomposing content into semantic atoms that candidate prose must preserve, then evaluates outputs in order of safety, semantic fidelity, accessibility, clarity, domain correctness, register fit, and ornament. Its Relational Systems Register connects embodied experience, relationships, institutions, causality, and ethical stakes through consequential detail, subtext, and systems-conscious realism, demonstrating that expressive language can remain distinctive without becoming semantically unaccountable.",
    ]),
    capabilities: Object.freeze([
      "Semantic atomization",
      "Ordered candidate evaluation",
      "Passage-level register selection",
      "Relational Systems Register",
    ]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://github.com/howardhayden/lattice"]),
    limitations: Object.freeze([
      "The hah.dev Text to Lattice demonstrator is browser-local, requires WebGPU, and accepts at most 700 words.",
      "A review-required draft is not certified as semantically equivalent.",
      "The demonstrable release uses Cloudflare’s official testing profile; it provides no production anti-bot assurance, and its public reusable token can occupy all eight shared slots, so availability is not assured.",
    ]),
    emphasis: Object.freeze(["linguistic register", "semantic fidelity", "relational systems"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "governs-linguistic-register-for", target: "fog-of-sea", scope: "naval learning and operational uncertainty" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "chorus", scope: "social and epistemic systems" }),
      Object.freeze({ relation: "governs-linguistic-register-for", target: "evenward", scope: "selected embodied guidance and care" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "Lattice Source Repository", url: "https://github.com/howardhayden/lattice", icon: "backpack4", opensInNewTab: true }),
      ...LATTICE_DOCUMENTATION_RESOURCES,
      LATTICE_RELEASE_QUALIFICATION_RESOURCE,
    ]),
    publication: Object.freeze({ label: "September 2026", value: "2026-09", precision: "month" }),
    status: "public",
    interaction: "lattice-demo",
    interactiveRelease: "enabled",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "in-keeping",
    slug: "in-keeping",
    name: "IN KEEPING",
    type: "SoftwareApplication",
    canonicalPath: "/projects/in-keeping/",
    url: "https://inkeep.ing/",
    icon: "bricks",
    thesis: "IN KEEPING keeps a library’s evidence, obligations, and recovery paths legible through change.",
    summary: Object.freeze([
      "IN KEEPING keeps a library’s evidence, obligations, and recovery paths legible through change.",
      "This local-first continuity lab gives people explicit workspaces, persistence, integrity-linked revisions, structured safeguards, and notebooks. It models dependencies and access paths; records custody, fixity, rights, metadata, conditions, decisions, and recovery actions; and preserves provenance through disruption and handoff.",
    ]),
    capabilities: Object.freeze(["User-created workspaces", "Integrity-linked revisions", "Custody and fixity records", "Continuity and recovery planning"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://inkeep.ing/?view=reports"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["provenance", "continuity", "access paths"]),
    relationships: Object.freeze([
      Object.freeze({ relation: "operationalizes", target: "provenance-continuity", scope: "custody, fixity, recovery, and handoff" }),
    ]),
    resources: Object.freeze([
      Object.freeze({ label: "IN KEEPING Technical Report", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "IN KEEPING Public Notice", url: "https://inkeep.ing/?view=reports", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "fog-of-sea",
    slug: "fog-of-sea",
    name: "FOG OF SEA",
    type: "VideoGame",
    canonicalPath: "/projects/fog-of-sea/",
    url: "https://fogofsea.app/",
    icon: "airplane-engines",
    thesis: "FOG OF SEA turns naval uncertainty into a quiet, learnable field of consequence.",
    summary: Object.freeze([
      "FOG OF SEA turns naval uncertainty into a quiet, learnable field of consequence.",
      "This single-player strategy game nests stochastic matrices within deterministic systems so that uncertainty remains observable without becoming arbitrary. Local-first privacy, resilient data handling, and accessibility support a cozy-sublime interface in which tactical information remains diegetic and decisions carry legible consequences.",
    ]),
    capabilities: Object.freeze(["Naval strategy learning", "Deterministic systems", "Local-first data handling", "Accessible tactical interaction"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["operational uncertainty", "naval learning"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "naval learning and operational uncertainty" })]),
    resources: Object.freeze([
      Object.freeze({ label: "FOG OF SEA Systems Atlas", url: "https://nbviewer.org/github/howardhayden/fogofsea/blob/main/docs/Systems-Atlas.ipynb", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "chorus",
    slug: "chorus",
    name: "CHORUS",
    type: "VideoGame",
    canonicalPath: "/projects/chorus/",
    url: "https://chorus.observer/",
    icon: "diagram-3",
    thesis: "CHORUS makes collective belief visible as a system of influence, uncertainty, and consequence.",
    summary: Object.freeze([
      "CHORUS makes collective belief visible as a system of influence, uncertainty, and consequence.",
      "This multi-agent social simulation models disinformation propagation, algorithmic amplification, social capital, and cross-scenario effects through interconnected actors. Procedural scenarios and network-scale coherence checks keep state changes traceable as one system’s pressures become another system’s conditions.",
    ]),
    capabilities: Object.freeze(["Multi-agent social systems", "Disinformation propagation", "Procedural scenarios", "Cross-system coherence validation"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://chorus.observer/notebooks/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["social systems", "epistemic systems", "collective belief"]),
    relationships: Object.freeze([Object.freeze({ relation: "applies-lattice-to", target: "lattice", scope: "social and epistemic systems" })]),
    resources: Object.freeze([
      Object.freeze({ label: "CHORUS Notebooks", url: "https://chorus.observer/notebooks/", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "CHORUS Concept Map", url: "https://chorus.observer/documentation/chorus-concept-map.html", icon: "backpack4", opensInNewTab: true }),
      Object.freeze({ label: "CHORUS CSD Matrix", url: "https://chorus.observer/documentation/chorus-csd-matrix.html", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "August 2026", value: "2026-08", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "evenward",
    slug: "evenward",
    name: "Evenward.rest",
    type: "SoftwareApplication",
    canonicalPath: "/projects/evenward/",
    url: "https://evenward.rest/",
    icon: "tree",
    thesis: "Evenward.rest treats self-regulation as an ecology of movement, attention, knowledge, and play.",
    summary: Object.freeze([
      "Evenward.rest treats self-regulation as an ecology of movement, attention, knowledge, and play.",
      "This privacy-conscious studio prototype brings embodied guidance, pattern practice, and local interaction into one quiet environment. Its parts are designed to reinforce one another, allowing care to emerge through relationships among movement, attention, knowledge, and play rather than through a single prescribed routine.",
    ]),
    capabilities: Object.freeze(["Movement guidance", "Attention and pattern practice", "Privacy-conscious local interaction"]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://evenward.rest/"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["embodied interaction", "care", "self-regulation"]),
    relationships: Object.freeze([Object.freeze({ relation: "selectively-applies-lattice-to", target: "lattice", scope: "embodied guidance and care" })]),
    resources: Object.freeze([
      Object.freeze({ label: "Evenward.rest Studio", url: "https://evenward.rest/", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "July 2026", value: "2026-07", precision: "month" }),
    status: "public",
    readmeAfterFirstParagraph: true,
  }),
  Object.freeze({
    id: "medium",
    slug: "medium",
    name: "Medium",
    type: "CollectionPage",
    canonicalPath: "/projects/medium/",
    url: "https://medium.com/@howardhayden",
    icon: "archive",
    thesis: "These essays trace the quiet infrastructure that shapes how people act under pressure.",
    summary: Object.freeze([
      "These essays trace the quiet infrastructure that shapes how people act under pressure.",
      "They examine the routines, institutions, tools, and maintenance work that make action possible before a crisis becomes visible. Each essay follows relationships among preparation, constraint, and consequence so that ordinary systems can be understood as conditions of collective life rather than as background.",
    ]),
    capabilities: Object.freeze([]),
    technologies: Object.freeze([]),
    evidence: Object.freeze(["https://medium.com/@howardhayden"]),
    limitations: Object.freeze([]),
    emphasis: Object.freeze(["infrastructure", "work under pressure"]),
    relationships: Object.freeze([]),
    resources: Object.freeze([
      Object.freeze({ label: "Howie’s Medium Articles", url: "https://medium.com/@howardhayden", icon: "backpack4", opensInNewTab: true }),
    ]),
    publication: Object.freeze({ label: "June 2026–present", value: "2026-06", precision: "open-range" }),
    status: "ongoing",
    readmeAfterFirstParagraph: true,
  }),
]);

export function projectBySlug(slug) {
  return projects.find((project) => project.slug === slug) ?? null;
}
